/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assignment3.h"
#include <stdlib.h>
#include <stdio.h>
void
rpc_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *function_hostname_1_arg;
	mergeOut  *result_2;
	mergeIn  function_mergesort_1_arg;
	char * *result_3;
	char * function_encryptedecho_1_arg;
	char *  *result_4;
	char * function_listfiles_1_arg;
	complexNum  *result_5;
	addComplex  function_addcomplex_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PROG, RPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    
    
    int option;
    
    
    while(1)
        
    {
        // the following functions can be implemented
        printf("The functions you can perform are :\n");
        
        printf("1. hostName\n");
        
        printf("2. addComplex\n");
        
        printf("3. listFiles\n");
        
        printf("4. encryptedEcho\n");
        
        printf("5. mergeSort\n");
        
        printf("6. Exit\n");
        
        printf("choose the option to perform a function \n");
        
        scanf("%d",&option);
        
        if(option == 1)
            
        {
            // calling the function for finding host name
            result_1 = function_hostname_1((void*)&function_hostname_1_arg, clnt);
            
            if (result_1 == (char **) NULL) {
                
                clnt_perror (clnt, "call failed");
                
            }
            
            printf("The Hostname is %s\n",*result_1);
            
        }
        
        else if (option == 2)
            
        {
            //taking input complex numbers
            printf("Taking the user input\n");
            printf("Enter the real part of  1st Complex Number \n");
            
            scanf("%d",&function_addcomplex_1_arg.input1.real);
            printf("Enter the imaginary part of 1st Complex Number without i \n");
            
            scanf("%d",&function_addcomplex_1_arg.input1.imaginary);
            
            
            
            
            printf("Enter the real part of 2nd Complex Number \n");
            scanf("%d",&function_addcomplex_1_arg.input2.real);
            printf("Enter the imaginary part of  2nd Complex Number without i \n");
            scanf("%d",&function_addcomplex_1_arg.input2.imaginary);
            // calling the function for finding the addition of complex numbers
            
            result_5 = function_addcomplex_1(&function_addcomplex_1_arg, clnt);
            
            if (result_5 == (complexNum *) NULL) {
                
                clnt_perror (clnt, "call failed");
                
            }
            
            printf("Result after adding the numbers\n");
            
            printf("%d ",result_5->real);
            if(result_5->imaginary< 0)
            {
                printf("%di\n",result_5->imaginary);
            }
            else
            {
                printf("+%di\n",result_5->imaginary);
            }
            
        }
        
        else if (option == 3)
            
        {
            
            
             function_listfiles_1_arg = (char*)malloc((100 + 1)*sizeof(char));
             
             printf("Enter directory path\n");
            scanf("%s",function_listfiles_1_arg);
            
            result_4 = function_listfiles_1(&function_listfiles_1_arg, clnt);
            printf("%s",*result_4);
           
            
            //printf("%s\n",*result_3);
            
            //          if (result_3 == (dirList **) NULL) {
            
            //            clnt_perror (clnt, "call failed");
            
            //      }
            
        }
        
        else if (option == 4)
            
        {
            
            //allocating dynamically
            function_encryptedecho_1_arg = (char*)malloc((100 + 1)*sizeof(char));
            
            printf("Enter String to encrypt\n");
            
            scanf("%s",function_encryptedecho_1_arg);
            // calling the function for encrypting
            result_3 = function_encryptedecho_1(&function_encryptedecho_1_arg, clnt);
            
            printf("Encrypted String\n");
            printf("%s\n",*result_3);
            
            if (result_3 == (char **) NULL) {
                
                clnt_perror (clnt, "call failed");
                
            }
            
        }
        
        else if (option == 5)
            
        {
            int size1,size2,i;
            // taking input list size
            printf("Enter size of array 1\n");
            scanf("%d",&size1);
            function_mergesort_1_arg.mergeInput1.mergeInput1_len = size1;
            function_mergesort_1_arg.mergeInput1.mergeInput1_val =  (int*)malloc((size1)*sizeof(int));
            printf("Enter array 1 numbers\n");
            for( i=0;i<size1;i++)
            {
                scanf("%d",function_mergesort_1_arg.mergeInput1.mergeInput1_val+i);
            }
            
            printf("Enter array 2 size\n");
            scanf("%d",&size2);
            function_mergesort_1_arg.mergeInput2.mergeInput2_len = size2;
            function_mergesort_1_arg.mergeInput2.mergeInput2_val =  (int*)malloc((size2)*sizeof(int));
            printf("Enter array 2 numbers \n");
            for(i=0;i<size2;i++)
            {
                scanf("%d",function_mergesort_1_arg.mergeInput2.mergeInput2_val+i);
            }
            printf("Merge Sort Result\n");
            result_2 = function_mergesort_1(&function_mergesort_1_arg, clnt);
            for(i=0;i<size1+size2;i++)
            {
                printf("%d ",*(result_2->mergeOutput.mergeOutput_val+i));
            }
            printf("\n");
            if (result_2 == (mergeOut *) NULL) {
                
                clnt_perror (clnt, "call failed");
                
            }
            
        }
        
        else
            
        {
            
            break;
            
        }
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_prog_1 (host);
exit (0);
}
