/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGNMENT3_H_RPCGEN
#define _ASSIGNMENT3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct mergeIn {
	struct {
		u_int mergeInput1_len;
		int *mergeInput1_val;
	} mergeInput1;
	struct {
		u_int mergeInput2_len;
		int *mergeInput2_val;
	} mergeInput2;
};
typedef struct mergeIn mergeIn;

struct mergeOut {
	struct {
		u_int mergeOutput_len;
		int *mergeOutput_val;
	} mergeOutput;
};
typedef struct mergeOut mergeOut;

struct complexNum {
	int real;
	int imaginary;
};
typedef struct complexNum complexNum;

struct addComplex {
	complexNum input1;
	complexNum input2;
};
typedef struct addComplex addComplex;

#define RPC_PROG 0x22347678
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FUNCTION_HOSTNAME 1
extern  char ** function_hostname_1(void *, CLIENT *);
extern  char ** function_hostname_1_svc(void *, struct svc_req *);
#define FUNCTION_MERGESORT 2
extern  mergeOut * function_mergesort_1(mergeIn *, CLIENT *);
extern  mergeOut * function_mergesort_1_svc(mergeIn *, struct svc_req *);
#define FUNCTION_ENCRYPTEDECHO 3
extern  char ** function_encryptedecho_1(char **, CLIENT *);
extern  char ** function_encryptedecho_1_svc(char **, struct svc_req *);
#define FUNCTION_LISTFILES 4
extern  char ** function_listfiles_1(char **, CLIENT *);
extern  char ** function_listfiles_1_svc(char **, struct svc_req *);
#define FUNCTION_ADDCOMPLEX 5
extern  complexNum * function_addcomplex_1(addComplex *, CLIENT *);
extern  complexNum * function_addcomplex_1_svc(addComplex *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FUNCTION_HOSTNAME 1
extern  char ** function_hostname_1();
extern  char ** function_hostname_1_svc();
#define FUNCTION_MERGESORT 2
extern  mergeOut * function_mergesort_1();
extern  mergeOut * function_mergesort_1_svc();
#define FUNCTION_ENCRYPTEDECHO 3
extern  char ** function_encryptedecho_1();
extern  char ** function_encryptedecho_1_svc();
#define FUNCTION_LISTFILES 4
extern  char ** function_listfiles_1();
extern  char ** function_listfiles_1_svc();
#define FUNCTION_ADDCOMPLEX 5
extern  complexNum * function_addcomplex_1();
extern  complexNum * function_addcomplex_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mergeIn (XDR *, mergeIn*);
extern  bool_t xdr_mergeOut (XDR *, mergeOut*);
extern  bool_t xdr_complexNum (XDR *, complexNum*);
extern  bool_t xdr_addComplex (XDR *, addComplex*);

#else /* K&R C */
extern bool_t xdr_mergeIn ();
extern bool_t xdr_mergeOut ();
extern bool_t xdr_complexNum ();
extern bool_t xdr_addComplex ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASSIGNMENT3_H_RPCGEN */
